session_name: dotfiles
windows:
  - window_name: dotfiles
    layout: main-vertical
    options:
      main-pane-width: 50%
    shell_command_before: cd ~/.dotfiles
    panes:
      - nvim
      - blank
