{ self, inputs, ... }: {
  flake.nixosModules.stanHardware =
    # Do not modify this file!  It was generated by ‘nixos-generate-config’
    # and may be overwritten by future invocations.  Please make changes
    # to /etc/nixos/configuration.nix instead.
    {
      config,
      lib,
      pkgs,
      modulesPath,
      ...
    }:

    {
      imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
      ];

      boot.consoleLogLevel = 0;
      boot.initrd.availableKernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
        "usbhid"
        "usb_storage"
        "sd_mod"
      ];
      boot.initrd.kernelModules = [
        "amdgpu"
      ];
      boot.initrd.verbose = false;
      boot.plymouth.enable = true;
      boot.kernelModules = [
        "kvm-amd"
        "ntsync"
      ];
      boot.kernelParams = [
        "quiet"
        "udev.log_level=3"
        "amdgpu.lockup_timeout=5000,10000,10000,5000"
        "amdgpu.sched_hw_submission=4"
      ];
      boot.kernel.sysctl = {
        "kernel.split_lock_mitigate" = 0;
        "kernel.nmi_watchdog" = 0;
        "kernel.sched_bore" = "1";
      };
      boot.extraModulePackages = [ ];

      fileSystems."/" = {
        device = "/dev/disk/by-uuid/cc6b0b3e-7676-4373-9ad6-bfcc95c0260e";
        fsType = "ext4";
      };

      fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/3055-0BCB";
        fsType = "vfat";
        options = [
          "fmask=0077"
          "dmask=0077"
        ];
      };

      swapDevices = [ ];

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.enableRedistributableFirmware = true;
      hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
      hardware.graphics = {
        enable = true;
        enable32Bit = true;
      };
    };
}
